altayland/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mycart/', include('mycart.urls', namespace='mycart')),
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

admin.autodiscover()

mycart/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),    
]

mycart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=55, db_index=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=300, db_index=True)
    slug = models.SlugField(max_length=320, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    period = models.CharField(max_length=25)                                        # 旅行時間
    main_image = models.ImageField(upload_to='products/main')                   # 顯示產品主要圖片（只顯示1張）
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, related_name='products')
    description = models.TextField()
    itinerary = models.TextField()                                                  # 旅行路線
    q_and_a = models.TextField(blank=True)                                          # 常見問題Q&A

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images')                     # 每一個產品可以有多張其他的圖片
    image = models.ImageField(upload_to='products/detail', blank=True)     # 可以用於顯示產品的詳細圖片

mycart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mycart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('mycart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('mycart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'mycart/cart_detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from mycart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    product_list = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product_list = Product.objects.filter(category=category)
    paginator = Paginator(product_list, 6)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop/product/list.html', {'category': category, 
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product':product, 'cart_product_form':cart_product_form})

mycart/templates/mycart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Your shopping cart - Altayland
{% endblock %}

{% block content %}
<div id="cart-detail-page">
	<h1>Your shopping cart</h1>
	<table class="cart">
		<thead>
			<tr>
				<th>destination</th>
				<th>period</th>
				<th>quantity</th>
				<th>remove</th>
				<th style="text-align:right;">unit price</th>
				<th style="text-align:right;">price</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
			{% with product=item.product %}
			<tr>
				<td>{{ product.name }}</td>
				<td>{{ product.period }}</td>
				<td>
					<form action="{% url 'mycart:cart_add' product.id %}" method="post">
						{{ item.update_quantity_form.quantity }}
						{{ item.update_quantity_form.update }}
						<input type="submit" value="更新">
						{% csrf_token %}
					</form>
				</td>
				<td><a href="{% url 'mycart:cart_remove' product.id %}">删除</a></td>
				<td class='num'>￥{{ item.price }}</td>
				<td class='num'>￥{{ item.total_price }}</td>
			</tr>
			{% endwith %}
			{% endfor %}
			<tr class="total">
				<td>Total</td>
				<td colspan='4'></td>
				<td class="num">￥{{ cart.get_total_price }}</td>
			</tr>
		</tbody>
	</table>
	<p class="text-right">
		<a href="{% url 'shop:product_list' %}" class="button light">继续购物</a>
		<a href="#" class="button">结算</a>
	</p>
</div>
{% endblock content %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Welcome to Altayland{% endblock %}</title>           
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href="/" class="logo">Altayland</a>
        </div>
        {% block subheader %}
        <div id="subheader">
            <div class="destination">
                <a href="/mainland-china/">mainland china</a>
            </div>
            <div class="destination">
                <a href="/south-korea/">south korea</a>
            </div>
            <div class="destination">
                <a href="/serbia/">serbia</a>
            </div>
            <div class="destination">
                <a href="/taiwan/">taiwan</a>
            </div>
            <div class="destination">
                <a href="/laos/">laos</a>
            </div>
			<div id="cart">
				<a href="{% url 'mycart:cart_detail' %}">my cart</a>
			</div>
        </div>
        {% endblock subheader %}
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        
    </body>
</html>

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}

{% block title %}{{ product.name }} - Altayland{% endblock %}

{% block content %}
    <div id="main">
        <div id="main-pic">
            <img src="{{ product.main_image.url }}">
        </div>
        <div id="middle-part">
            <div id="product-name">{{ product.name }}</div>
            <div id="product-period">{{ product.period }}</div>
            <div id="product-price">rmb {{ product.price }}</div>
            <form action="{% url 'mycart:cart_add' product.id %}" method="post">
				<div id="selectbar">
					{{ cart_product_form }}
					{% csrf_token %}
					<input type='submit' id="addToCart" value='添加到购物车'>
				</div>
            </form>
        </div>
        
    </div>
    <div id="text-detail">
       <div class="info-box" id="description">
           <h3>description</h3>
           <p>{{ product.description|linebreaks }}</p>
       </div>
       <div class="info-box" id="itinerary">
           <h3>itinerary</h3>
           <p>{{ product.itinerary|linebreaks }}</p>
       </div>
       <div class="info-box" id="q_and_a">
           <h3>q and a</h3>
           <p>{{ product.q_and_a|linebreaks }}</p>
       </div>    
    </div>
    
    <div id="pic-detail">
        {% for pic in product.images.all %}
            <img src="{{ pic.image.url }}">
        {% endfor %}
    </div>
    <div id="bottom">
            <div id="about">
                <h3>about</h3>
                <p><span style="font-family:DaxCompact-Regular; ">altayland</span>专注于高品质旅游，目前开通台湾、南韩、老挝、中国大陆及塞尔维亚线路。</p>
            </div>
            <div id="contact">
                <h3>contact</h3>
                <p><span style="font-family:DaxCompact-Regular; ">e-mail: info@altayland.com</span></p>
            </div>    
    </div>

{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }} - Altayland{% else %}Altayland{% endif %}
{% endblock %}

{% block content %}
    <div id="grid">
        {% for p in products %}
            <div class="item">
                <a href="{{ p.get_absolute_url }}">
                    <img src="{{ p.main_image.url }}">
                </a><br />
                <a href="{{ p.get_absolute_url }}">
                    {{ p.name }}
                </a>
            </div>
        {% endfor %}
    </div>
    <div id="pagination1">
    {% include 'shop/product/pagination.html' %}
    </div>
    <div id="bottom">
            <div id="about">
                <h3>about</h3>
                <p><span style="font-family:DaxCompact-Regular; ">altayland</span>专注于高品质旅游，目前开通台湾、南韩、老挝、中国大陆及塞尔维亚线路。</p>
            </div>
            <div id="contact">
                <h3>contact</h3>
                <p><span style="font-family:DaxCompact-Regular; ">e-mail: info@altayland.com</span></p>
            </div>    
    </div>       
           
{% endblock %}

shop/templates/shop/product/pagination.html
<div id="pagination">
    <span class="step-links">
        {% if products.has_previous %}
            <a href="?page={{ products.previous_page_number }}">pevious</a>
        {% endif %}
        <span class="current" style="color: black;">
            page{{ products.number }} of {{ products.paginator.num_pages }}
        </span>
        {% if products.has_next %}
            <a href="?page={{ products.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>